apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "stateful.fullname" . }}
  labels:
    type: local
  annotations:
    "helm.sh/resource-policy": keep
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName:  {{ include "stateful.fullname" . }}-local
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}